### PR TITLE
fixes #70: remove un-necessary constructors from expression

### LINKED ISSUE #70: can't create a constexpr expression
having expression<> as an aggregate would allow the following to work:
`constexpr auto e = make_expression<yap::expression, expr_kind::terminal>(1);`

The compiler should generate useful default constructors anyway. Can we do without the constructor taking a hana::tuple as an r-value?

### PR DESCRIPTION
**Pull request by rgrover**

### CODE REVIEW

**Comment by tzlaine** [comment]
This is unnecessary for what we really want -- to make expression<> constexpr.  This has latter change just been committed.

**Comment by rgrover** [comment]
What I would really like to have is the ability to initialize an expression like an aggregate. With the help of a deduction guide, such as
```C++
template <typename T>
expression(T)->expression<expr_kind::terminal, boost::hana::tuple<T>>;
```

I can then write `expression{1}`

**Comment by tzlaine** [comment]
CTAD works with ctors.  Define one for expression<> if you like, and construct expression<>s with "expression(1)".  Does that not work for some reason?

**Comment by rgrover** [comment]
yes, CTAD works with constructors. I essentially want constexpr expression. thanks.

**Pull request closed without merging**
